### ISSUE TITLE
General info

### ISSUE THREAD

**Issue by pawloaka** [fsi-open/datagrid-bundle#111]
Hi, 

I would like to use your package to display a list/table of users on my website:
- I would like to have the option to sort this list by some fields
- I would like to have pagination
- I would like to have a search box, where I can search, for example by username

My questions are:
1) What is the difference between `fsi-open/datagrid-bundle` and` fsi-open/datagrid`? Which bundle should I use to achieve the functionalities listed above?
2) How to do it?

Thanks in advance!

**Comment by szymach** [comment]
In short:
- https://github.com/fsi-open/datagrid displays data,
- https://github.com/fsi-open/datasource fetches data and is used for filtering/ordering the results that you display in `datagrid`.

`datagrid/source-bundle` packages are basically used to integrate with Symfony, not much else. Having 4 (5 if you count https://github.com/fsi-open/data-indexer) separate packages is a bit of an over-engineered approach we took when creating these packages, which we aim to rectify by merging them into one in the future. The namespaces will remain the same, so migration should not be much of an issue.

Anyways, `datasource` has a README on how to use it. You can use https://github.com/fsi-open/admin-bundle (with https://github.com/fsi-open/admin-security-bundle) if you want a complete package and have a CMS or you can use these components separately more or less like this:

```php
        // create instances of your datagrid/source
        $dataSource = $this->createDataSource();
        $dataGrid = $this->createDataGrid();

        $parameters = [];
        parse_str($uri->getQuery(), $parameters);
        $dataSource->bindParameters($parameters);

        /** @var Countable&IteratorAggregate $result */
        $result = $dataSource->getResult();
        $dataGrid->setData($result);
        foreach ($dataGrid as $row) {
            // display rows
        }
```
