### ISSUE TITLE
Create a custom collection form type for editable cells

### ISSUE THREAD

**Issue by szymach** [fsi-open/datagrid-bundle#73]
This way we can remove the collection buttons from it's block.

**Comment by norzechowicz** [comment]
can't we just check if form type is collection and display or not those buttons?

**Comment by szymach** [comment]
It is always collection type. Using a different form type for editable rows prevents us from accidentally braking something in the default collection type block.

**Comment by norzechowicz** [comment]
Why even this button is there? Form type is always a collection in order to support multiple editable fields for the same column. Maybe removing that button at all is a solution?

**Comment by szymach** [comment]
OK turns out it they are only added in admin-bundle, so this issue is redundant.
